@startuml
note as N1
  <size:16><b>Factory Method (Before)

end note

object Cliente

class Celular {
    # long id;
    # String nome;
    # String sistemaOperacional;
    # BigDecimal preco;
    + getters()
    + setters()
    + String toString()
}

class IphoneXSMax {
    +Celular criarCelular();
}

class MotorolaEdge50Pro {
    +Celular criarCelular();
}

class SamsungGalaxyS24Ultra {
    +Celular criarCelular();
}

Cliente .[#blue].> Celular :use
Cliente .[#blue].> IphoneXSMax :use
Cliente .[#blue].> MotorolaEdge50Pro :use
Cliente .[#blue].> SamsungGalaxyS24Ultra :use

class IphoneXSMax extends Celular
class MotorolaEdge50Pro extends Celular
class SamsungGalaxyS24Ultra extends Celular
@enduml
